name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update known hosts
      run: |
        ssh-keyscan -t rsa 45.152.114.177 >> ~/.ssh/known_hosts

    - name: Deploy to remote server
      run: |
        ssh minerac@45.152.114.177 "cd /var/www/danya && git pull origin develop"
